name: ocs
version: '${project.version}'
main: nl.midnan.onechunksurvival.OneChunkSurvival
api-version: 1.18
authors: [ Midnan ]
description: Survive on one-chunk, grow your world by advancements.
website: midnan.tv
