package nl.midnan.onechunksurvival;

import java.util.HashMap;
import java.util.Map;

public class AdvancementLookupTable {

    static Map<String, String> ADVANCEMENT_NAMES;

    public AdvancementLookupTable() {
        ADVANCEMENT_NAMES = new HashMap<>();
        ADVANCEMENT_NAMES.put("minecraft:adventure/adventuring_time", "Adventuring Time");
        ADVANCEMENT_NAMES.put("minecraft:adventure/kill_a_mob, ", "Monster Hunter");
        ADVANCEMENT_NAMES.put("minecraft:adventure/kill_all_mobs", "Monsters Hunted");
        ADVANCEMENT_NAMES.put("minecraft:adventure/root", "Adventure Advancement");
        ADVANCEMENT_NAMES.put("minecraft:adventure/shoot_arrow", "Take Aim");
        ADVANCEMENT_NAMES.put("minecraft:adventure/sleep_in_bed", "Sweet dreams");
        ADVANCEMENT_NAMES.put("minecraft:adventure/sniper_duel", "Sniper duel");
        ADVANCEMENT_NAMES.put("minecraft:adventure/summon_iron_golem", "Hired Help");
        ADVANCEMENT_NAMES.put("minecraft:adventure/throw_trident", "A Throwaway Joke");
        ADVANCEMENT_NAMES.put("minecraft:adventure/totem_of_undying", "Postmortal");
        ADVANCEMENT_NAMES.put("minecraft:adventure/trade", "What a Deal");
        ADVANCEMENT_NAMES.put("minecraft:adventure/very_very_frightening", "Very Very Frightening");
        ADVANCEMENT_NAMES.put("minecraft:end/dragon_breath", "You Need a Mint");
        ADVANCEMENT_NAMES.put("minecraft:end/dragon_egg", "The Next Generation");
        ADVANCEMENT_NAMES.put("minecraft:end/elytra", "Sky's the Limit");
        ADVANCEMENT_NAMES.put("minecraft:end/enter_end_gateway", "Remote Getaway");
        ADVANCEMENT_NAMES.put("minecraft:end/find_end_city", "End Advancementaa");
        ADVANCEMENT_NAMES.put("minecraft:end/kill_dragon", "Free the End");
        ADVANCEMENT_NAMES.put("minecraft:end/levitate", "Great View From Up Here");
        ADVANCEMENT_NAMES.put("minecraft:end/respawn_dragon", "The End... Again...");
        ADVANCEMENT_NAMES.put("minecraft:end/root", "End Advancement");
        ADVANCEMENT_NAMES.put("minecraft:husbandry/balanced_diet", "A Balanced Diet");
        ADVANCEMENT_NAMES.put("minecraft:husbandry/break_diamond_hoe", "Serious Dedication");
        ADVANCEMENT_NAMES.put("minecraft:husbandry/bred_all_animals", "Two by Two");
        ADVANCEMENT_NAMES.put("minecraft:husbandry/breed_an_animal", "Husbandry Advancement");
        ADVANCEMENT_NAMES.put("minecraft:husbandry/plant_seed", "A Seedy Place");
        ADVANCEMENT_NAMES.put("minecraft:husbandry/root", "Husbandry Advancement");
        ADVANCEMENT_NAMES.put("minecraft:husbandry/tactical_fishing", "Tactical Fishing");
        ADVANCEMENT_NAMES.put("minecraft:husbandry/tame_an_animal", "Best Friends Forever");
        ADVANCEMENT_NAMES.put("minecraft:nether/all_effects", "How Did We Get Here?");
        ADVANCEMENT_NAMES.put("minecraft:nether/all_potions", "A Furious Cocktail");
        ADVANCEMENT_NAMES.put("minecraft:nether/brew_potion", "Local Brewery");
        ADVANCEMENT_NAMES.put("minecraft:nether/create_beacon", "Bring Home the Beacon");
        ADVANCEMENT_NAMES.put("minecraft:nether/create_full_beacon", "Beaconator");
        ADVANCEMENT_NAMES.put("minecraft:nether/fast_travel", "Subspace Bubble");
        ADVANCEMENT_NAMES.put("minecraft:nether/find_fortress", "A Terrible Fortress");
        ADVANCEMENT_NAMES.put("minecraft:nether/get_wither_skull", "Spooky Scary Skeleton");
        ADVANCEMENT_NAMES.put("minecraft:nether/obtain_blaze_rod", "Into Fire");
        ADVANCEMENT_NAMES.put("minecraft:nether/return_to_sender", "Return to Sender");
        ADVANCEMENT_NAMES.put("minecraft:nether/root", "Nether Advancement");
        ADVANCEMENT_NAMES.put("minecraft:nether/summon_wither", "Withering Heights");
        ADVANCEMENT_NAMES.put("minecraft:nether/uneasy_alliance", "Uneasy Alliance");
        ADVANCEMENT_NAMES.put("minecraft:recipes/brewing/blaze_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/brewing/brewing_stand", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/brewing/cauldron", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/brewing/fermented_spider_eye", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/brewing/glass_bottle", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/brewing/golden_carrot", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/brewing/magma_cream", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/brewing/speckled_melon", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/acacia_bark", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/acacia_planks", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/acacia_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/acacia_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/andesite", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/birch_bark", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/birch_planks", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/birch_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/birch_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/black_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/black_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/black_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/black_wool", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/blue_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/blue_ice", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/blue_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/blue_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/blue_wool", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/bone_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/bookshelf", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/brick_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/brick_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/bricks", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/brown_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/brown_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/brown_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/brown_wool", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/chiseled_quartz_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/chiseled_red_sandstone", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/chiseled_sandstone", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/chiseled_stone_brick", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/clay", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/coal_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/coarse_dirt", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/cobblestone_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/cobblestone_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/cracked_stone_brick", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/cut_red_sandstone", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/cut_sandstone", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/cyan_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/cyan_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/cyan_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/cyan_wool", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/dark_oak_bark", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/dark_oak_planks", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/dark_oak_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/dark_oak_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/dark_prismarine", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/dark_prismarine_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/dark_prismarine_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/diamond_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/diorite", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/dried_kelp_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/emerald_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/end_stone_bricks", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/glowstone", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/gold_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/granite", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/gray_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/gray_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/gray_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/gray_wool", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/green_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/green_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/green_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/green_wool", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/hay_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/iron_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/jack_o_lantern", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/jungle_bark", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/jungle_planks", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/jungle_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/jungle_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/lapis_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/light_blue_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/light_blue_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/light_blue_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/light_blue_wool", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/light_gray_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/light_gray_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/light_gray_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/light_gray_wool", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/lime_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/lime_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/lime_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/lime_wool", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/magenta_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/magenta_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/magenta_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/magenta_wool", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/magma_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/melon_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/mossy_cobblestone", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/mossy_stone_bricks", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/nether_brick", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/nether_brick_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/nether_brick_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/nether_bricks", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/nether_wart_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/oak_bark", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/oak_planks", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/oak_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/oak_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/orange_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/orange_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/orange_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/orange_wool", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/pink_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/pink_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/pink_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/pink_wool", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/polished_andesite", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/polished_diorite", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/polished_granite", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/prismarine", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/prismarine_bricks", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/prismarine_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/prismarine_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/purple_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/purple_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/purple_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/purple_wool", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/purpur_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/purpur_pillar", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/purpur_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/purpur_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/quartz_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/quartz_pillar", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/quartz_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/quartz_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/red_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/red_nether_bricks", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/red_sandstone", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/red_sandstone_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/red_sandstone_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/red_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/red_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/red_wool", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/sandstone", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/sandstone_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/sandstone_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/sea_lantern", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/snow_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/sponge", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/spruce_bark", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/spruce_planks", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/spruce_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/spruce_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/stone", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/stone_brick_slab", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/stone_brick_stairs", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/stone_bricks", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/white_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/white_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/white_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/white_wool_from_string", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/yellow_concrete_powder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/yellow_stained_glass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/yellow_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/building_blocks/yellow_wool", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/arrow", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/bow", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/diamond_boots", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/diamond_chestplate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/diamond_helmet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/diamond_leggings", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/diamond_sword", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/golden_boots", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/golden_chestplate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/golden_helmet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/golden_leggings", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/golden_sword", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/iron_boots", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/iron_chestplate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/iron_helmet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/iron_leggings", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/iron_sword", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/leather_boots", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/leather_chestplate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/leather_helmet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/leather_leggings", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/shield", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/spectral_arrow", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/stone_sword", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/turtle_helmet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/combat/wooden_sword", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/acacia_fence", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/anvil", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/armor_stand", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/birch_fence", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/black_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/black_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/black_bed_from_white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/black_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/black_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/black_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/blue_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/blue_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/blue_bed_from_white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/blue_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/blue_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/blue_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/brown_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/brown_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/brown_bed_from_white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/brown_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/brown_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/brown_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/chest", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/cobblestone_wall", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/crafting_table", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/cyan_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/cyan_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/cyan_bed_from_white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/cyan_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/cyan_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/cyan_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/dark_oak_fence", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/enchanting_table", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/end_crystal", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/end_rod", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/ender_chest", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/fence", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/flower_pot", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/furnace", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/gray_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/gray_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/gray_bed_from_white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/gray_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/gray_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/gray_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/green_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/green_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/green_bed_from_white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/green_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/green_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/green_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/iron_bars", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/item_frame", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/jukebox", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/jungle_fence", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/ladder", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/light_blue_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/light_blue_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/light_blue_bed_from_white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/light_blue_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/light_blue_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/light_blue_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/light_gray_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/light_gray_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/light_gray_bed_from_white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/light_gray_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/light_gray_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/light_gray_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/lime_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/lime_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/lime_bed_from_white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/lime_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/lime_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/lime_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/magenta_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/magenta_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/magenta_bed_from_white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/magenta_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/magenta_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/magenta_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/mossy_cobblestone_wall", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/nether_brick_fence", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/orange_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/orange_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/orange_bed_from_white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/orange_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/orange_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/orange_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/painting", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/pink_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/pink_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/pink_bed_from_white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/pink_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/pink_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/pink_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/purple_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/purple_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/purple_bed_from_white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/purple_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/purple_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/purple_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/red_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/red_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/red_bed_from_white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/red_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/red_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/red_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/shulker_box", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/sign", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/slime_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/snow", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/spruce_fence", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/torch", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/white_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/white_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/white_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/white_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/yellow_banner", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/yellow_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/yellow_bed_from_white_bed", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/yellow_carpet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/yellow_glazed_terracotta", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/decorations/yellow_stained_glass_pane", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/baked_potato", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/beetroot_soup", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/bread", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/cake", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/cooked_beef", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/cooked_chicken", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/cooked_cod", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/cooked_mutton", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/cooked_porkchop", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/cooked_rabbit", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/cooked_salmon", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/cookie", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/dried_kelp", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/dried_help_from_smelting", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/golden_apple", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/mushroom_stew", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/pumpkin_pie", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/rabbit_stew_from_brown_mushroom", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/food/rabbit_stew_from_red_mushroom", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/beacon", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/bone_meal", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/bone_meal_from_bone_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/book", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/bowl", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/brick", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/bucket", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/cactus_green", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/charcoal", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/chorus_fruit_popped", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/coal", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/coal_from_smelting", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/conduit", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/cyan_dye", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/diamond", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/diamond_from_smelting", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/emerald", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/emerald_from_smelting", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/ender_eye", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/fire_charge", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/gold_ingot", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/gold_ingot_from_gold_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/gold_ingot_from_nuggets", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/gold_nugget", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/gold_nugget_from_smelting", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/gray_dye", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/iron_ingot", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/iron_ingot_from_iron_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/iron_ingot_from_nuggets", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/iron_nugget", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/iron_nugget_from_smelting", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/lapis_from_smelting", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/lapis_lazuli", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/leather", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/light_blue_dye_from_blue_orchid", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/light_blue_dye_from_lapis_bonemeal", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/light_gray_dye_from_azure_bluet", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/light_gray_dye_from_gray_bonemeal", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/light_gray_dye_from_ink_bonemeal", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/light_gray_dye_from_oxeye_daisy", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/light_gray_dye_from_white_tulip", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/lime_dye", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/lime_dye_from_smelting", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/magenta_dye_from_allium", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/magenta_dye_from_lapis_ink_bonemeal", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/magenta_dye_from_lapis_red_pink", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/magenta_dye_from_lilac", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/magenta_dye_from_purple_and_pink", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/map", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/melon_seeds", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/nether_brick", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/orange_dye_from_orange_tulip", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/orange_dye_from_red_yellow", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/paper", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/pink_dye_from_peony", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/pink_dye_from_pink_tulip", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/pink_dye_from_red_bonemeal", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/pumpkin_seeds", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/purple_dye", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/quartz", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/red_dye_from_beetroot", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/red_dye_from_poppy", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/red_dye_from_rose_bush", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/red_dye_from_tulip", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/slime_ball", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/stick", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/sugar", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/wheat", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/writable_book", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/yellow_dye_from_dandelion", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/misc/yellow_dye_from_sunflower", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/acacia_button", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/acacia_door", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/acacia_fence_gate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/acacia_pressure_plate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/acacia_trapdoor", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/birch_button", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/birch_door", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/birch_fence_gate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/birch_pressure_plate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/birch_trapdoor", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/comparator", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/dark_oak_button", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/dark_oak_door", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/dark_oak_fence_gate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/dark_oak_pressure_plate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/dark_oak_trapdoor", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/daylight_detector", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/dispenser", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/dropper", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/fence_gate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/heavy_weighted_pressure_plate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/hopper", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/iron_door", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/iron_trapdoor", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/jungle_button", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/jungle_door", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/jungle_fence_gate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/jungle_pressure_plate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/jungle_trapdoor", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/lever", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/light_weighted_pressure_plate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/note_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/oak_button", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/oak_door", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/oak_fence_gate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/oak_pressure_plate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/oak_trapdoor", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/observer", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/piston", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/redstone", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/redstone_block", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/redstone_from_smelting", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/redstone_lamp", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/redstone_torch", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/repeater", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/spruce_button", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/spruce_door", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/spruce_fence_gate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/spruce_pressure_plate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/spruce_trapdoor", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/sticky_piston", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/stone_button", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/stone_pressure_plate", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/tnt", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/trapped_chest", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/redstone/tripwire_hook", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/root", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/clock", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/compass", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/diamond_axe", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/diamond_hoe", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/diamond_pickaxe", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/diamond_shovel", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/fishing_rod", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/flint_and_steel", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/golden_axe", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/golden_hoe", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/golden_pickaxe", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/golden_shovel", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/iron_axe", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/iron_hoe", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/iron_pickaxe", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/iron_shovel", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/lead", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/shears", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/stone_axe", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/stone_hoe", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/stone_pickaxe", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/stone_shovel", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/wooden_axe", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/wooden_hoe", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/wooden_pickaxe", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/tools/wooden_shovel", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/acacia_boat", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/activator_rail", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/birch_boat", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/carrot_on_a_stick", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/chest_minecart", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/dark_oak_boat", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/detector_rail", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/furnace_minecart", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/hopper_minecart", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/jungle_boat", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/minecart", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/oak_boat", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/powered_rail", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/rail", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/spruce_boat", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:recipes/transportation/tnt_minecart", "Recipe");
        ADVANCEMENT_NAMES.put("minecraft:story/cure_zombie_villager", "Zombie Doctor");
        ADVANCEMENT_NAMES.put("minecraft:story/deflect_arrow", "Not Today, Thank You");
        ADVANCEMENT_NAMES.put("minecraft:story/enchant_item", "Enchanter");
        ADVANCEMENT_NAMES.put("minecraft:story/enter_the_end", "The End?");
        ADVANCEMENT_NAMES.put("minecraft:story/enter_the_nether", "We Need to Go Deeper");
        ADVANCEMENT_NAMES.put("minecraft:story/follow_ender_eye", "Eye Spy");
        ADVANCEMENT_NAMES.put("minecraft:story/form_obsidian", "Ice Bucket Challenge");
        ADVANCEMENT_NAMES.put("minecraft:story/iron_tools", "Isn't It Iron Pick");
        ADVANCEMENT_NAMES.put("minecraft:story/lava_bucket", "Hot Stuff");
        ADVANCEMENT_NAMES.put("minecraft:story/mine_diamond", "Diamonds");
        ADVANCEMENT_NAMES.put("minecraft:story/mine_stone", "Stone Age");
        ADVANCEMENT_NAMES.put("minecraft:story/obtain_armor", "Suit Up");
        ADVANCEMENT_NAMES.put("minecraft:story/root", "Story Advancement");
        ADVANCEMENT_NAMES.put("minecraft:story/shiny_gear", "Cover Me with Diamonds");
        ADVANCEMENT_NAMES.put("minecraft:story/smelt_iron", "Acquire Hardware");
        ADVANCEMENT_NAMES.put("minecraft:story/upgrade_tools", "Getting an Upgrade");
    }

    public String get(String key) {
        return ADVANCEMENT_NAMES.getOrDefault(key, key);
    }
}
